sut:
  build: ./integration-tests
  links:
    - survey-service
survey-service:
  build: ./survey-service
  ports:
    - "3000:3000"
  links:
  - mongo
mongo:
  image: mongo
  volumes:
  - ./data:/data"
  ports:
  - "27027:27017"
